# Generated by Django 3.0.2 on 2025-06-18 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage',
            old_name='mamo',
            new_name='memo',
        ),
        migrations.AlterField(
            model_name='manage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Category'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
